spring:
  datasource:
    url: jdbc:h2:mem:agro
    driver-class-name: org.h2.Driver
    data-username: agro
    data-password: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: off
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog-master.xml
